version: '3.0'

services:
  api:
    env_file:
      - .env
    build: 
      context: .
    volumes:
      - ./:/home/node/app
      - $HOME/.npmrc:/home/node/.npmrc
      - $HOME/ssh:/home/node/.ssh
    links:
      - db
    ports:
      - 8081:8081

  db:
    image: postgres:16.2
    hostname: db
    volumes:
      - ./devops/sql/ddl.sql:/docker-entrypoint-initdb.d/script.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
